version: "3.9"

services:
  database:
    image: postgres:17
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_PASSWORD: not_so_secret
      POSTGRES_USER: postgres
      POSTGRES_DB: dev
    volumes:
      - database_volume:/var/lib/postgresql
  api:
    build: services/api
    restart: always
    environment:
      DATABASE_URL: "postgresql://postgres:not_so_secret@database:5431/dev"
    ports:
      - "5001:5001"

volumes:
  database_volume:
